export default {
    bodyText: '#333',
    bodyColor: '#fff',
    btnDefault: '#2699fb',
    btnDefaultText: '#fff',
    borderDefault: '#e6e6e6',
    borderDeep: '#ccc',
    delete: '#dc3545',
    headerText: '#000',
    menuBackground: '#4eacfc', 
    menuText: '#fff',
    radioBorder: '#000',
    shadowDefault: '#333',
    snackbarBackground: '#4eacfc',
    snackbarText: '#fff',
    snackbarBtn: '#2691fb',
    snackbarBtnText: '#fff',
    success: '#28a745',
    warning: '#ffc107'
}